name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
    - name: Deploy to Raspberry Pi
      run: |
        ${{ vars.SSH_COMMAND }} << 'EOF'
          cd /home/samuel/raspberrypi-plant-humidity-webpage
          git pull
          ./restart.sh
        EOF
